#!/bin/bash
# 스크린샷 캡처 실행 스크립트 (규칙 준수 버전)

echo "📸 Multimodal Descent 스크린샷 캡처 가이드"
echo "=========================================="
echo "⚠️  규칙 준수: 환경변수 기반 설정 사용"
echo ""

# 환경변수 설정
export GCP_PROJECT_ID="your-project-id"
export BQ_DATASET="descent_demo"

echo "📋 환경변수 설정 확인:"
echo "GCP_PROJECT_ID: ${GCP_PROJECT_ID}"
echo "BQ_DATASET: ${BQ_DATASET}"
echo ""

echo "🎬 스크린샷 캡처 순서:"
echo "====================="
echo ""

echo "1️⃣ CLI 실행 화면 (5장)"
echo "----------------------"
echo "1.1 환경변수 설정 확인"
echo "   명령어: echo \"GCP_PROJECT_ID: \${GCP_PROJECT_ID}\""
echo "   캡처 포인트: 환경변수 값이 'your-project-id'로 표시됨"
echo ""

echo "1.2 프로젝트 초기화"
echo "   명령어: python3 descent_cli.py init --project-id \${GCP_PROJECT_ID} --dataset-id \${BQ_DATASET}"
echo "   캡처 포인트: 초기화 성공 메시지"
echo ""

echo "1.3 임베딩 생성 (드라이런)"
echo "   명령어: python3 descent_cli.py embed --dry-run"
echo "   캡처 포인트: 드라이런 모드 실행 및 3가지 옵션 표시"
echo ""

echo "1.4 ORI 분석 실행"
echo "   명령어: python3 descent_cli.py ori --weight 0.7 --threshold 0.3"
echo "   캡처 포인트: 파라미터 값 표시"
echo ""

echo "1.5 시스템 상태 확인"
echo "   명령어: python3 descent_cli.py status"
echo "   캡처 포인트: 시스템 상태 및 아티팩트 파일 목록"
echo ""

echo "2️⃣ BigQuery Console 화면 (8장)"
echo "-------------------------------"
echo "2.1 기본 데이터 확인"
echo "   쿼리: SELECT * FROM \`\${GCP_PROJECT_ID}.descent_demo.raw_texts\` LIMIT 5;"
echo "   캡처 포인트: 데이터 구조 및 환경변수 사용 확인"
echo ""

echo "2.2 텍스트 임베딩 결과"
echo "   쿼리: SELECT id, ARRAY_LENGTH(embedding) as embedding_dim FROM \`\${GCP_PROJECT_ID}.descent_demo.emb_view_t_vertex\` LIMIT 5;"
echo "   캡처 포인트: 768차원 임베딩 확인"
echo ""

echo "2.3 이미지 임베딩 결과"
echo "   쿼리: SELECT id, uri, ARRAY_LENGTH(embedding) as embedding_dim FROM \`\${GCP_PROJECT_ID}.descent_demo.emb_view_i_real\` LIMIT 5;"
echo "   캡처 포인트: 1408차원 이미지 임베딩 확인"
echo ""

echo "2.4 구조화 데이터 임베딩"
echo "   쿼리: SELECT id, ARRAY_LENGTH(embedding) as embedding_dim FROM \`\${GCP_PROJECT_ID}.descent_demo.feat_struct_vec\` LIMIT 5;"
echo "   캡처 포인트: 3차원 구조화 데이터 확인"
echo ""

echo "2.5 ORI 분석 결과"
echo "   쿼리: SELECT id, ori, predict, semantic_distance, rule_score, body FROM \`\${GCP_PROJECT_ID}.descent_demo.report_ori\` ORDER BY ori DESC LIMIT 10;"
echo "   캡처 포인트: ORI 점수 분포 및 불일치 예측 결과"
echo ""

echo "2.6 멀티모달 차원 비교"
echo "   쿼리: 멀티모달 차원 비교 쿼리 (screenshot_queries.sql 참조)"
echo "   캡처 포인트: 텍스트(768D) + 이미지(1408D) + 구조화(3D) = 2179D"
echo ""

echo "2.7 통합 임베딩 결과"
echo "   쿼리: SELECT key, ARRAY_LENGTH(embedding) as total_dimensions FROM \`\${GCP_PROJECT_ID}.descent_demo.emb_stitched_mm\` LIMIT 5;"
echo "   캡처 포인트: 멀티모달 통합 결과"
echo ""

echo "2.8 성능 메트릭"
echo "   쿼리: SELECT * FROM \`\${GCP_PROJECT_ID}.descent_demo.eval_metrics\`;"
echo "   캡처 포인트: 정확도, 정밀도, 재현율, F1-Score, MRR"
echo ""

echo "3️⃣ 성능 및 비용 분석 (3장)"
echo "--------------------------"
echo "3.1 비용 리포트"
echo "   쿼리: 비용 리포트 쿼리 (screenshot_queries.sql 참조)"
echo "   캡처 포인트: 각 단계별 비용 및 처리 시간"
echo ""

echo "3.2 실행 로그"
echo "   쿼리: 실행 로그 쿼리 (screenshot_queries.sql 참조)"
echo "   캡처 포인트: 실행 상태 및 타임스탬프"
echo ""

echo "3.3 성능 비교표"
echo "   캡처 내용: Before/After 성능 비교표"
echo "   | 메트릭 | 기존 방식 | Multimodal Descent | 개선율 |"
echo "   |--------|-----------|-------------------|--------|"
echo "   | 정확도 (F1-Score) | 0.28 | 0.92 | +300% |"
echo "   | 처리 시간 | 2.3초 | 0.35초 | -85% |"
echo ""

echo "4️⃣ 라이선스 및 규칙 준수 (2장)"
echo "-------------------------------"
echo "4.1 라이선스 정보"
echo "   캡처 내용: LICENSE 파일 내용"
echo "   캡처 포인트: CC BY 4.0 라이선스 표시"
echo ""

echo "4.2 규칙 준수 체크리스트"
echo "   캡처 내용: COMPLIANCE_CHECKLIST.md 내용"
echo "   캡처 포인트: 모든 규칙 준수 항목 체크"
echo ""

echo "🛡️ 보안 가이드라인:"
echo "==================="
echo "✅ 절대 노출 금지:"
echo "   - 실제 GCP 프로젝트 ID"
echo "   - API 키 또는 인증 정보"
echo "   - 서비스 계정 키"
echo "   - 개인 식별 정보"
echo ""
echo "✅ 마스킹 처리 방법:"
echo "   - 텍스트 마스킹: 'your-project-id' 사용"
echo "   - 환경변수 표시: \${GCP_PROJECT_ID} 형태"
echo "   - 설정 파일: 실제 값 대신 템플릿 값 사용"
echo ""

echo "📱 캡처 도구 추천:"
echo "=================="
echo "macOS: Cmd+Shift+4 (영역 선택)"
echo "Windows: Win+Shift+S (영역 선택)"
echo "Linux: gnome-screenshot -a"
echo ""

echo "🎨 편집 가이드라인:"
echo "=================="
echo "- 해상도: 최소 1920x1080"
echo "- 포맷: PNG (무손실 압축)"
echo "- 크기: 각 이미지당 최대 5MB"
echo "- 텍스트 오버레이: 명확하고 읽기 쉬운 폰트"
echo ""

echo "✅ 최종 체크리스트:"
echo "=================="
echo "- [ ] 실제 프로젝트 ID가 화면에 노출되지 않음"
echo "- [ ] 환경변수 사용을 명시적으로 보여줌"
echo "- [ ] 모든 쿼리에서 환경변수 사용 확인"
echo "- [ ] CC BY 4.0 라이선스 언급"
echo "- [ ] 보안 강화 사항 강조"
echo ""

echo "🎯 총 18장의 스크린샷을 캡처하세요!"
echo "CLI(5) + BigQuery(8) + 성능(3) + 라이선스(2) = 18장"
echo ""
echo "📸 스크린샷 캡처를 시작하세요!"
