dataset_id: descent_demo
dry_run: false
enable_cost_logging: true
enable_incremental: true
location: US
max_retries: 3
mode: vertex
ori_threshold: 0.3
ori_weight: 0.7
project_id: your-project-id
retry_delay: 1.0
top_k: 10
